# Generated by Django 3.2.8 on 2021-10-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_employee_chief'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='wages',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Зарплата'),
            preserve_default=False,
        ),
    ]
